assignment3:	Date.o main.o Table.o Reservation.o Time.o RsvList.o Restaurant.o Control.o View.o
	g++ -o assignment3 Date.o main.o Table.o Reservation.o Time.o RsvList.o Restaurant.o Control.o View.o

Date.o:	Date.cc Date.h
	g++ -c Date.cc

main.o: main.cc
	g++ -c main.cc

Table.o: Table.cc Table.h
	g++ -c Table.cc

Reservation.o:	Reservation.cc Reservation.h
	g++ -c Reservation.cc

Time.o:	Time.cc Time.h
	g++ -c Time.cc

RsvList.o: RsvList.cc RsvList.h
	g++ -c RsvList.cc

Restaurant.o: Restaurant.cc Restaurant.h
	g++ -c Restaurant.cc

Control.o: Control.cc Control.h
	g++ -c Control.cc

View.o: View.cc View.h
	g++ -c View.cc

clean: 
	rm *.o assignment3